---
name: Setup R dependencies
author: Insights Engineering
description: GitHub Action to install R package dependencies

inputs:
  repository-path:
    description: Directory where the R package is located relative to the calling GitHub workflow workspace.
    required: false
    default: "."
  lookup-refs:
    description: |
      List of package references to be used for the feature branch.
      Multiple entries in new lines or separated by commas.
      Only GitHub references are supported.
    required: false
    default: ""
  dependencies:
    description: Passed to `r-lib/actions/setup-r-dependencies`.
    required: false
    default: '"all"'
  extra-packages:
    description: Passed to `r-lib/actions/setup-r-dependencies`.
    required: false
    default: ""
  install-quarto:
    description: Passed to `r-lib/actions/setup-r-dependencies`.
    required: false
    default: "auto"
  cache-version:
    description: Passed to `r-lib/actions/setup-r-dependencies`.
    required: true
    default: 1
  needs:
    description: |
      Passed to `r-lib/actions/setup-r-dependencies`.
      The value will be amended by `DepsBranch` and `DepsDev` values.
    required: false
    default: ""
  skip-desc-branch:
    description: Skip the DESCRIPTION file modification for the feature branch.
    required: false
    default: false
  skip-desc-dev:
    description: Skip the DESCRIPTION file modification for the development branch.
    required: false
    default: false
  skip-install:
    description: Skip the installation of R package dependencies.
    required: false
    default: false
  max-iter:
    description: Maximum number of iterations to resolve dependencies.
    required: false
    default: 10
  repository-list:
    description: |
      Comma-separated list of pkgcache-compatible repository names from which the dependencies will be downloaded.
      Optionally, list elements can be named in the form of `name=repo_name`.
    required: false
    default: "PPM=PPM@latest"
  restore-description:
    description: |
      Whether the DESCRIPTION file (modified by this action) should be restored to its original contents?
    required: false
    default: true

branding:
  icon: 'download'
  color: 'orange'

runs:
  using: composite
  steps:

  - name: Get branch names
    id: branch-names
    uses: tj-actions/branch-names@v8

  - name: Normalize inputs
    id: normalizer
    run: |
      echo "::group::Normalize input variables"
      # Normalize the repository path
      repopath="${{ inputs.repository-path }}"
      repopath=$(echo "${repopath%%/.*}")
      echo "repository-path=${repopath}" >> $GITHUB_OUTPUT
      echo "::endgroup::"
    shell: bash

  - name: Get current branch or tag 🏷️
    id: current-branch-or-tag
    run: |
      if [ "${{ steps.branch-names.outputs.is_tag }}" == "true" ]; then
        echo "Current tag: ${{ steps.branch-names.outputs.tag }}"
        echo "ref-name=${{ steps.branch-names.outputs.tag }}" >> $GITHUB_OUTPUT
      else
        echo "Current branch: ${{ steps.branch-names.outputs.current_branch }}"
        echo "ref-name=${{ steps.branch-names.outputs.current_branch }}" >> $GITHUB_OUTPUT
      fi
    shell: bash

  - name: Copy DESCRIPTION
    if: ${{ inputs.restore-description == 'true' }}
    run: |
      # Copy DESCRIPTION
      echo "::group::Copy DESCRIPTION"
      temp_desc=$(mktemp)
      cp ${{ steps.normalizer.outputs.repository-path }}/DESCRIPTION $temp_desc
      echo "TEMP_DESCRIPTION=$temp_desc" >> $GITHUB_ENV
      ls -l $temp_desc
      echo "::endgroup::"
    shell: bash

  - name: Install required packages
    uses: r-lib/actions/setup-r-dependencies@v2
    with:
      packages: ""
      extra-packages: |
        any::sessioninfo
        any::pkgdepends
        any::cli
        any::desc
        any::pkgcache
      install-pandoc: false
      install-quarto: false

  - name: Set R option "repos"
    run: |
      cat > ${HOME}/.Rprofile <<EOF
      input <- "${{ inputs.repository-list }}"
      repos_to_add <- sapply(
        trimws(strsplit(input, ",")[[1]]),
        function(x) {
          if (grepl("=", x)) {
            x <- strsplit(x, "=")[[1]]
            stats::setNames(pkgcache::repo_resolve(x[2]), x[1])
          } else {
            stats::setNames(pkgcache::repo_resolve(x), x)
          }
        },
        USE.NAMES = FALSE
      )
      options(repos = c(repos_to_add, getOption("repos")))
      EOF
      echo "::group::Show R option 'repos'"
      echo $(Rscript -e 'x <- getOption("repos"); for (i in seq_along(x)) { print(sprintf("%s = %s", names(x)[i], x[[i]])) }')
      echo "::endgroup::"
    shell: bash

  - name: Define utils
    id: utils
    shell: Rscript {0}
    run: |
      # Define utils
      cat("::group::Define utils\n")
      desc_field_append <- function(d, key, value) {
        old_values <- d$get_field(key)
        old_values_v <- parse_input(old_values)
        new_values_v <- unique(c(old_values_v, value))
        new_values <- paste(new_values_v, collapse = ", ")
        d$set_list(key, new_values)
      }
      desc_field_clear_if_empty <- function(d, key) {
        if (desc_empty_field(d, key)) {
          d$del(key)
        }
      }
      find_ref <- function(package, refs) {
        res <- Filter(
          x = pkgdepends::parse_pkg_refs(refs),
          f = function(ref) {
            ref$package == package
          }
        )
        if (length(res) == 0) {
          return(NULL)
        }
        if (length(res) > 1) {
          warning(sprintf("Multiple refs found for package %s. Only the first one will be used.", package))
        }
        res <- res[[1]]
        if (isFALSE(is(res, "remote_ref_github"))) {
          warning(sprintf("Ref for package %s is not a GitHub type of ref.", package))
          return(NULL)
        }
        return(res)
      }
      remote_ref_add_branch <- function(remote_ref, branch_name) {
        pkgdepends::parse_pkg_ref(
          sprintf(
            "%s@%s",
            gsub(
              "//@.*",
              "",
              remote_ref$ref
            ),
            branch_name
          )
        )
      }
      remote_ref_ping <- function(remote_ref) {
        x <- pkgdepends::new_pkg_deps(remote_ref$ref, config = list(dependencies = FALSE))
        x$solve()
        x$get_solution()$status == "OK"
      }
      new_pkg_deps <- function(refs) {
        pkgdepends::new_pkg_deps(
          refs,
          config = list(
            dependencies = c(
              sprintf("Config/Needs/%s", strsplit("${{ inputs.needs }}", "[[:space:],]+")[[1]]),
              "Config/Needs/DepsBranch",
              "Config/Needs/DepsDev",
              pkgdepends::as_pkg_dependencies(${{ inputs.dependencies }})$direct
            )
          )
        )
      }
      parse_input <- function(input) {
        trimws(strsplit(x = gsub("\n", ",", input), split = ",")[[1]])
      }
      
      desc_empty_field <- function(d, field) {
        d$has_fields(field) && !nzchar(d$get_field(field, ""))
      }
      
      desc_get_field_vec <- function(d, field) {
         parse_input(d$get_field(field, ""))
      }
      
      log_vars <- function(...) {
        args <- list(...)
        arg_names <- substitute(...())
        for (i in seq_along(args)) {
          cli::cli_alert_info("Variable {.code {arg_names[[i]]}}: {.val {args[[i]]}}.")
        }
      }
      cat("::endgroup::\n")
      cat("::group::Save utils\n")
      save.image(file = "utils.R")
      cat("::endgroup::\n")

  - name: Prepare DESCRIPTION file (feature branch)
    if: >
      inputs.skip-desc-branch == 'false' &&
      steps.branch-names.outputs.is_default != 'true' &&
      inputs.lookup-refs != ''
    id: desc-branch
    shell: Rscript {0}
    run: |
      # Prepare DESCRIPTION file (feature branch)
      cat("::group::Load utils\n")
      load("utils.R")
      cat("::endgroup::\n")

      cat("::group::Parse inputs\n")
      path <- parse_input("${{ steps.normalizer.outputs.repository-path }}")
      lookup_refs <- parse_input("${{ inputs.lookup-refs }}")
      current_branch <- parse_input("${{ steps.current-branch-or-tag.outputs.ref-name }}")
      log_vars(path, lookup_refs, current_branch)
      cat("::endgroup::\n")

      cat("::group::Assertions\n")
      if (isFALSE(file.exists(file.path(path, "DESCRIPTION")))) {
        cli::cli_alert_danger("{.file DESCRIPTION} file not found in {.path {path}}. Skipping.")
        cat("::endgroup::\n")
        q(save = "no")
      }
      parsed_lookup_refs <- pkgdepends::parse_pkg_refs(lookup_refs)
      if (any(!vapply(parsed_lookup_refs, is, logical(1), "remote_ref_github"))) {
        incorrect_idx <- which(!vapply(parsed_lookup_refs, is, logical(1), "remote_ref_github"))
        cli::cli_alert_danger("All lookup refs must be GH refs. Incorrect refs: {.val {lookup_refs[incorrect_idx]}}.")
        cat("::endgroup::\n")
        q(save = "no")
      }
      cat("::endgroup::\n")

      cat("::group::Modify DESCRIPTION file (feature branch)\n")
      d <- desc::desc(path)
      d$set_list("Config/Needs/DepsBranch", character(0))

      x <- new_pkg_deps(sprintf("local::%s", path))
      x$resolve()
      deps <- x$get_resolution()$package

      for (i_ref in lookup_refs) {
        cli::cli_alert_info("Processing lookup reference {.field {i_ref}}.")

        i_remote_ref <- pkgdepends::parse_pkg_ref(i_ref)
        i_package <- i_remote_ref$package

        if (isFALSE(i_package %in% deps)) {
          cli::cli_alert_info("Package {.pkg {i_package}} is not a dependency. Skipping.")
          next
        }

        i_remote_ref_branch <- remote_ref_add_branch(i_remote_ref, current_branch)
        if (isFALSE(remote_ref_ping(i_remote_ref_branch))) {
          cli::cli_alert_info("Feature branch {.field {current_branch}} does not exist for reference {.field {i_ref}}. Skipping.")
          next
        }

        desc_field_append(d, "Config/Needs/DepsBranch", i_remote_ref_branch$ref)
        cli::cli_alert_success("Reference {.field {i_remote_ref_branch$ref}} added to the {.field Config/Needs/DepsBranch} field.")
      }

      desc_field_clear_if_empty(d, "Config/Needs/DepsBranch")
      d$write(path)
      cat("::endgroup::\n")

      cat("::group::Print added field\n")
      cat(d$get("Config/Needs/DepsBranch"))
      cat("\n")
      cat("::endgroup::\n")

      cat("::group::Print DESCRIPTION file\n")
      d
      cat("::endgroup::\n")

  - name: Prepare DESCRIPTION file (development)
    if: >
      ${{ inputs.skip-desc-dev == 'false' }} &&
      ${{ inputs.lookup-refs != '' }}
    id: desc-dev
    shell: Rscript {0}
    run: |
      # Prepare DESCRIPTION file (development)
      cat("::group::Load utils\n")
      load("utils.R")
      cat("::endgroup::\n")

      cat("::group::Parse inputs\n")
      path <- parse_input("${{ steps.normalizer.outputs.repository-path }}")
      lookup_refs <- parse_input("${{ inputs.lookup-refs }}")
      max_iter <- as.integer("${{ inputs.max-iter }}")
      log_vars(path, lookup_refs, max_iter)
      cat("::endgroup::\n")

      cat("::group::Assertions\n")
      if (isFALSE(file.exists(file.path(path, "DESCRIPTION")))) {
        cli::cli_alert_danger("{.file DESCRIPTION} file not found in {.path {path}}. Skipping.")
        cat("::endgroup::\n")
        q(save = "no")
      }
      parsed_lookup_refs <- pkgdepends::parse_pkg_refs(lookup_refs)
      if (any(!vapply(parsed_lookup_refs, is, logical(1), "remote_ref_github"))) {
        incorrect_idx <- which(!vapply(parsed_lookup_refs, is, logical(1), "remote_ref_github"))
        cli::cli_alert_danger("All lookup refs must be GH refs. Incorrect refs: {.val {lookup_refs[incorrect_idx]}}.")
        cat("::endgroup::\n")
        q(save = "no")
      }
      cat("::endgroup::\n")

      cat("::group::Modify DESCRIPTION file (development)\n")
      d <- desc::desc(path)
      d$set_list("Config/Needs/DepsDev", character(0))

      x <- new_pkg_deps(sprintf("local::%s", path))
      x$solve()

      i <- 0L
      failures_message_prev <- NULL
      while (TRUE) {
        i <- i + 1L

        if (i > max_iter) {
          cli::cli_alert_danger("Maximum number of iterations reached. Exiting.")
          break()
        }

        x$solve()

        if (x$get_solution()$status == "OK") {
          cli::cli_alert_success("Dependencies resolved successfully.")
          break()
        }

        failures <- x$get_solution()$failures
        failed_refs <- unique(unlist(failures[, "failure_down"]))
        cli::cli_alert_warning("Failed to resolve dependencies.")
        cli::cli_text("Error:")
        cat(format(failures))
        cat("\n")
        cli::cli_text("End of error")
        cli::cli_text("Failed refs: {.pkg {failed_refs}}.")

        failure_message <- failures$failure_message
        if (identical(failure_message, failures_message_prev)) {
          cli::cli_alert_danger("Failed to resolve dependencies. No progress. Exiting.")
          break()
        }
        failures_message_prev <- failure_message

        for (failed_ref in failed_refs) {
          pkg <- pkgdepends::parse_pkg_ref(failed_ref)$package
          pkg_ref <- find_ref(pkg, lookup_refs)

          # skip if not found
          if (length(pkg_ref) == 0) {
            cli::cli_alert_danger("Package {.pkg {pkg}} not found in the {.code lookup_refs} list: {.val {lookup_refs}}. Skipping.")
            next()
          }

          # skip if already there
          if (pkg_ref$ref %in% desc_get_field_vec(d, "Config/Needs/DepsDev")) {
            cli::cli_alert_info("Reference for package {.pkg {pkg}} already exists in the {.field Config/Needs/DepsDev} field. Skipping.")
            next()
          }

          # skip if already in `DepsBranch`
          # this is to avoid duplicates - `Deps Branch` takes precedence over `DepsDev`
          if (
            (!identical(desc_get_field_vec(d, "Config/Needs/DepsBranch"), "")) &&
            (pkg %in% vapply(desc_get_field_vec(d, "Config/Needs/DepsBranch"), function(x) {if (x == "") { character(1L)} else {pkgdepends::parse_pkg_ref(x)$package}}, character(1)))
          ) {
            cli::cli_alert_info("A reference for package {.pkg {pkg}} already exists in the {.field Config/Needs/DepsBranch} field. Skipping.")
            next()
          }

          cli::cli_alert_info("Adding package {.pkg {pkg}} (ref: {.val {pkg_ref$ref}}) to the {.field Config/Needs/DepsDev} field.")
          desc_field_append(d, "Config/Needs/DepsDev", pkg_ref$ref)

          d$write(path)
        }

        cli::cli_alert_info("Trying to resolve dependencies again.")
        cli::cli_text("---")
        x <- new_pkg_deps(sprintf("local::%s", path))
      }

      desc_field_clear_if_empty(d, "Config/Needs/DepsDev")
      d$write(path)
      cat("::endgroup::\n")

      cat("::group::Print added field\n")
      cat(d$get("Config/Needs/DepsDev"))
      cat("\n")
      cat("::endgroup::\n")

      cat("::group::Print DESCRIPTION file\n")
      d
      cat("::endgroup::\n")

  - name: Remove utils
    id: remove-utils
    shell: bash
    run: |
      # Remove utils
      rm utils.R

  - name: Install Dependencies
    uses: r-lib/actions/setup-r-dependencies@v2
    if: ${{ inputs.skip-install == 'false' }}
    with:
      working-directory: ${{ steps.normalizer.outputs.repository-path }}
      extra-packages: ${{ inputs.extra-packages }}
      upgrade: 'TRUE'
      needs: |
        ${{ inputs.needs }}
        DepsBranch
        DepsDev
      dependencies: ${{ inputs.dependencies }}
      install-quarto: ${{ inputs.install-quarto }}
      cache-version: ${{ inputs.cache-version }}

  - name: Restore DESCRIPTION
    if: ${{ inputs.restore-description == 'true' }}
    run: |
      # Restore DESCRIPTION
      echo "::group::Restore DESCRIPTION"
      cp ${{ env.TEMP_DESCRIPTION }} ${{ steps.normalizer.outputs.repository-path }}/DESCRIPTION
      ls -l ${{ steps.normalizer.outputs.repository-path }}/DESCRIPTION
      echo "::endgroup::"
    shell: bash
